config/routes.rb
Rails.application.routes.draw do
  resources :forces
  resources :posts

  root 'welcome#index'

end

app/models/force.rb
class Force < ActiveRecord::Base
end

app/models/organo.rb
class Organo < ActiveRecord::Base
    belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
    validates :nombre, presence: true
    has_many :organos
    before_save :count_organos
    def count_organos
        puts "a este usuario le quedan #{self.count_organos}"
    end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forces_controller.rb
class ForcesController < ApplicationController
  before_action :set_force, only: [:show, :edit, :update, :destroy]

  # GET /forces
  # GET /forces.json
  def index
    @forces = Force.all
  end

  # GET /forces/1
  # GET /forces/1.json
  def show
  end

  # GET /forces/new
  def new
    @force = Force.new
  end

  # GET /forces/1/edit
  def edit
  end

  # POST /forces
  # POST /forces.json
  def create
    @force = Force.new(force_params)

    respond_to do |format|
      if @force.save
        format.html { redirect_to @force, notice: 'Force was successfully created.' }
        format.json { render :show, status: :created, location: @force }
      else
        format.html { render :new }
        format.json { render json: @force.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forces/1
  # PATCH/PUT /forces/1.json
  def update
    respond_to do |format|
      if @force.update(force_params)
        format.html { redirect_to @force, notice: 'Force was successfully updated.' }
        format.json { render :show, status: :ok, location: @force }
      else
        format.html { render :edit }
        format.json { render json: @force.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forces/1
  # DELETE /forces/1.json
  def destroy
    @force.destroy
    respond_to do |format|
      format.html { redirect_to forces_url, notice: 'Force was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_force
      @force = Force.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def force_params
      params.require(:force).permit(:Person, :user, :mail)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :desc)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forces_helper.rb
module ForcesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/forces/_form.html.erb
<%= form_for(@force) do |f| %>
  <% if @force.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@force.errors.count, "error") %> prohibited this force from being saved:</h2>

      <ul>
      <% @force.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Person %><br>
    <%= f.text_field :Person %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forces/edit.html.erb
<h1>Editing Force</h1>

<%= render 'form' %>

<%= link_to 'Show', @force %> |
<%= link_to 'Back', forces_path %>

app/views/forces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forces</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>User</th>
      <th>Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forces.each do |force| %>
      <tr>
        <td><%= force.Person %></td>
        <td><%= force.user %></td>
        <td><%= force.mail %></td>
        <td><%= link_to 'Show', force %></td>
        <td><%= link_to 'Edit', edit_force_path(force) %></td>
        <td><%= link_to 'Destroy', force, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Force', new_force_path %>

app/views/forces/new.html.erb
<h1>New Force</h1>

<%= render 'form' %>

<%= link_to 'Back', forces_path %>

app/views/forces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @force.Person %>
</p>

<p>
  <strong>User:</strong>
  <%= @force.user %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @force.mail %>
</p>

<%= link_to 'Edit', edit_force_path(@force) %> |
<%= link_to 'Back', forces_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootcamp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.desc %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @post.desc %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<div align=center>
	<h1>Feisbuk</h1>
</div>

<h1>Nombre</h1><input type="text" name="nombre" value="" />
<h1>Clave:</h1><input type="text" name="nombre" value="" />
<input type="button" name="Inviar" value="" />